Lab10_MVCVentas_Sosa/Controllers/ProductoController.cs
using Modelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab10_MVCVentas_Sosa.Filters;

namespace Lab10_MVCVentas_Sosa.Controllers
{
    [Autenticado]
    public class ProductoController : Controller
    {
        private PRODUCTO producto = new PRODUCTO();//Instancia la clase producto
        private CATEGORIA tipo = new CATEGORIA();
        // GET: Producto
        public ActionResult Index(string criterio)
        {
            if (criterio == null || criterio == "")
            {
                return View(producto.Listar());
            }
            else
            {
                return View(producto.Buscar(criterio));
            }
        }

        public ActionResult Ver(int id)
        {
            return View(producto.Obtener(id));
        }

        public ActionResult AgregarEditar(int id = 0)
        {
            return View(
                id == 0 ? new PRODUCTO() //para generar una nueva categoría
                        : producto.Obtener(id) //retorna un id de una categoría existente
                );
        }

        public ActionResult Guardar(PRODUCTO model)
        {
            if (ModelState.IsValid)
            {
                model.Guardar();
                return Redirect("~/Producto/Index"); //devuelve el index
            }
            else
            {
                return View("~/Views/Producto/AgregarEditar.cshtml", model);
            }
        }

        public ActionResult Eliminar(int id)
        {
            producto.IDPRODUCTO = id;
            producto.Eliminar();
            return Redirect("~/Producto/Index"); //devuelve el index
        }

        public ActionResult Buscar(string criterio)
        {
            return View(
                    criterio == null || criterio == "" ? producto.Listar()//devuelve la lista completa
                    : producto.Buscar(criterio)//devuelve la lista en base a la búsqueda
                    );
        }

        public ActionResult BuscarCategoria(int criterio = 0)
        {
            ViewBag.Combo = tipo.Listar();
            return View(producto.BuscarCategoria(criterio));
        }
    }
}

Lab10_MVCVentas_Sosa/Views/Producto/AgregarEditar.cshtml
@model Modelo.PRODUCTO
@{
    ViewBag.Title = (Model.IDPRODUCTO > 0 ? Model.NOMBRE : "Nuevo Registro");
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">Agregar/Editar Producto</h2>

<ol class="breadcrumb">
    <li>
        <a href="~/Producto/">Productos</a>
    </li>
    <li class="active">
        @(Model.IDPRODUCTO > 0 ? Model.NOMBRE : "Nuevo Registro")
    </li>
</ol>

@using (Html.BeginForm("Guardar", "Producto", FormMethod.Post, new { id = "frm-categoria" }))
{
    @Html.HiddenFor(x => x.IDPRODUCTO)

    <div class="panel panel-default">
        <div class="panel-heading">
            Información del Producto
        </div>
        <div class="panel-body">
            <div class="form-group">
                @Html.LabelFor(x => x.IDPRODUCTO)
                @Html.TextBoxFor(x => x.IDPRODUCTO, new { @class = "form-control", disabled = true })
                @Html.ValidationMessageFor(x => x.IDPRODUCTO, null, new { @class = "label label-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.IDCATEGORIA)
                @Html.TextBoxFor(x => x.IDCATEGORIA, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.IDCATEGORIA, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.NOMBRE)
                @Html.TextBoxFor(x => x.NOMBRE, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NOMBRE, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.DESCRIPCION)
                @Html.TextBoxFor(x => x.DESCRIPCION, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.DESCRIPCION, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.PRECIO)
                @Html.TextBoxFor(x => x.PRECIO, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.PRECIO, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.STOCK)
                @Html.TextBoxFor(x => x.STOCK, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.STOCK, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.PORTADA)
                <select name="estado" class="form-control">
                    <option @(Model.PORTADA == "S" ? "selected" : "") value="S">Sí</option>
                    <option @(Model.PORTADA == "N" ? "selected" : "") value="N">No</option>
                </select>
                @Html.ValidationMessageFor(x => x.PORTADA, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.IMPORTANCIA)
                @Html.TextAreaFor(x => x.IMPORTANCIA, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.IMPORTANCIA, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.IMAGEN)
                <select name="estado" class="form-control">
                    <option @(Model.IMAGEN == "S" ? "selected" : "") value="S">Sí</option>
                    <option @(Model.IMAGEN == "N" ? "selected" : "") value="N">No</option>
                </select>
                @Html.ValidationMessageFor(x => x.IMAGEN, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.ESTADO)
                <select name="estado" class="form-control">
                    <option @(Model.ESTADO == "A" ? "selected" : "") value="A">Activo</option>
                    <option @(Model.ESTADO == "I" ? "selected" : "") value="I">Inactivo</option>
                </select>
                @Html.ValidationMessageFor(x => x.ESTADO, null, new { @class = "label label-danger" })
            </div>
        </div>
    </div>

    <div class="text-right">
        <button type="submit" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span></button>
        <a href="~/Producto/Index" class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-floppy-remove" aria-hidden="true"></span></a>
    </div>
}

Lab10_MVCVentas_Sosa/Views/Producto/Buscar.cshtml
@model List<Modelo.PRODUCTO>
@{
    ViewBag.Title = "Buscar";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">
    Búsqueda de Productos
</h2>

@using (Html.BeginForm("Buscar", "Producto", FormMethod.Post, new { criterio = "frm-buscar" }))
{
    <div class="text-left">
        @Html.Label("Buscar: ")
        @Html.TextBox("criterio", null)
        <button type="submit" class="btn btn-lg btn-warning pull-right"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
}
<br />
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width:50px;">Id</th>
                <th style="width:200px;">Categoría</th>
                <th style="width:200px;">Nombre</th>
                <th style="width:200px;">Descripción</th>
                <th style="width:200px;">Precio</th>
                <th style="width:200px;">Stock</th>
                <th style="width:200px;">Portada</th>
                <th style="width:200px;">Importancia</th>
                <th style="width:200px;">Imagen</th>
                <th style="width:50px;">Estado</th>
                <th style="width:50px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <th>@(m.IDPRODUCTO)</th>
                    <th>@(m.IDCATEGORIA)</th>
                    <th>@(m.NOMBRE)</th>
                    <th>@(m.DESCRIPCION)</th>
                    <th>@(m.PRECIO)</th>
                    <th>@(m.STOCK)</th>
                    <th>@(m.PORTADA == "S" ? "Sí" : "No")</th>
                    <th>@(m.IMPORTANCIA)</th>
                    <th>@(m.IMAGEN == "S" ? "Sí" : "No")</th>
                    <th>@(m.ESTADO == "A" ? "Activo" : "Inactivo")</th>
                </tr>
            }
        </tbody>
    </table>
</div>

Lab10_MVCVentas_Sosa/Views/Producto/BuscarCategoria.cshtml
@model List<Modelo.PRODUCTO>
@{
    ViewBag.Title = "Consultas";
    Layout = "~/Views/Shared/Layout.cshtml";
    List<Modelo.CATEGORIA> tipo = ViewBag.Combo;
}

@using (Html.BeginForm("BuscarCategoria", "Producto", FormMethod.Post, new { criterio = "frm-buscar" }))
{
    <div class="text-left">
        <select name="criterio" class="form-control">
            @foreach (var t in tipo)
            {
                <option value="@t.IDCATEGORIA">@t.NOMBRE</option>
            }
        </select>
        <button type="submit" class="btn btn-lg btn-warning pull-right"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
}
<br />
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width:50px;">Id</th>
                <th style="width:200px;">Categoría</th>
                <th style="width:200px;">Nombre</th>
                <th style="width:200px;">Descripción</th>
                <th style="width:200px;">Precio</th>
                <th style="width:200px;">Stock</th>
                <th style="width:200px;">Portada</th>
                <th style="width:200px;">Importancia</th>
                <th style="width:200px;">Imagen</th>
                <th style="width:50px;">Estado</th>
                <th style="width:50px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <th>@(m.IDPRODUCTO)</th>
                    <th>@(m.CATEGORIA.NOMBRE)</th>
                    <th>@(m.NOMBRE)</th>
                    <th>@(m.DESCRIPCION)</th>
                    <th>@(m.PRECIO)</th>
                    <th>@(m.STOCK)</th>
                    <th>@(m.PORTADA == "S" ? "Sí" : "No")</th>
                    <th>@(m.IMPORTANCIA)</th>
                    <th>@(m.IMAGEN == "S" ? "Sí" : "No")</th>
                    <th>@(m.ESTADO == "A" ? "Activo" : "Inactivo")</th>
                </tr>
            }
        </tbody>
    </table>
</div>

Lab10_MVCVentas_Sosa/Views/Producto/Consulta.cshtml
@model List<Modelo.PRODUCTO>
@{
    ViewBag.Title = "Consulta";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width:50px;">Id</th>
                <th style="width:200px;">Nombre</th>
                <th style="width:200px;">Cantidad Producto</th>
                <th style="width:50px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <th>@(m.CATEGORIA.IDCATEGORIA)</th>
                    <th>@(m.CATEGORIA.NOMBRE)</th>
                    <th>@(m.STOCK)</th>
                </tr>
            }
        </tbody>
    </table>
</div>

Lab10_MVCVentas_Sosa/Views/Producto/Index.cshtml
@model List<Modelo.PRODUCTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">
    <a href="~/Producto/AgregarEditar/" class="btn btn-lg btn-success pull-right"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a>Productos
</h2>

@using (Html.BeginForm("Buscar", "Producto", FormMethod.Post, new { criterio = "frm-buscar" }))
{
    <div class="text-left">
        @Html.Label("Buscar: ")
        @Html.TextBox("criterio", null)
        <button type="submit" class="btn btn-lg btn-warning pull-right"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
}
<br />
<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width:50px;">Id</th>
                <th style="width:200px;">Categoría</th>
                <th style="width:200px;">Nombre</th>
                <th style="width:200px;">Descripción</th>
                <th style="width:200px;">Precio</th>
                <th style="width:200px;">Stock</th>
                <th style="width:200px;">Portada</th>
                <th style="width:200px;">Importancia</th>
                <th style="width:200px;">Imagen</th>
                <th style="width:50px;">Estado</th>
                <th style="width:50px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <th>@(m.IDPRODUCTO)</th>
                    <th>@(m.CATEGORIA.NOMBRE)</th>
                    <th>@(m.NOMBRE)</th>
                    <th>@(m.DESCRIPCION)</th>
                    <th>@(m.PRECIO)</th>
                    <th>@(m.STOCK)</th>
                    <th>@(m.PORTADA == "S" ? "Sí" : "No")</th>
                    <th>@(m.IMPORTANCIA)</th>
                    <th>@(m.IMAGEN == "S" ? "Sí" : "No")</th>
                    <th>@(m.ESTADO == "A" ? "Activo" : "Inactivo")</th>

                    <th>
                        <a href="~/Producto/Ver/@m.IDPRODUCTO" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
                        <a href="~/Producto/AgregarEditar/@m.IDPRODUCTO" class="btn btn-lg btn-info"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                        <a onclick="return confirm('¿Está seguro de eliminar el registro...?');" class="btn btn-lg btn-danger" href="~/Producto/Eliminar/@m.IDPRODUCTO"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

Lab10_MVCVentas_Sosa/Views/Producto/Ver.cshtml
@model Modelo.PRODUCTO
@{
    ViewBag.Title = "Ver";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">Ver Producto</h2>

<ol class="breadcrumb">

    <li><a href="~/">Producto</a></li>
    <li class="active">@Model.NOMBRE</li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading">
        Información de los Productos
    </div>
    <div>
        <dl class="dl-horizontal">
            <dt>ID</dt>
            <dd>@Model.IDPRODUCTO</dd>
            <dt>NOMBRE</dt>
            <dd>@Model.IDCATEGORIA</dd>
            <dt>ESTADO</dt>
            <dd>@Model.NOMBRE</dd>
            <dt>ID</dt>
            <dd>@Model.DESCRIPCION</dd>
            <dt>NOMBRE</dt>
            <dd>@Model.PRECIO</dd>
            <dt>ESTADO</dt>
            <dd>@Model.STOCK</dd>
            <dt>ID</dt>
            <dd>@Model.PORTADA</dd>
            <dt>NOMBRE</dt>
            <dd>@Model.IMPORTANCIA</dd>
            <dt>ESTADO</dt>
            <dd>@Model.IMAGEN</dd>
            <dt>ESTADO</dt>
            <dd>@Model.ESTADO</dd>
        </dl>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        Detalles de Pedidos
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width:50px;">Id Pedido</th>
                    <th style="width:50px;">Id Producto</th>
                    <th style="width:200px;">Precio</th>
                    <th style="width:200px;">Cantidad</th>
                    <th style="width:50px;"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var d in Model.DETALLE_PEDIDO)
                {
                    <tr>
                        <th>@(d.IDPEDIDO)</th>
                        <th>@(d.IDPRODUCTO)</th>
                        <th>@(d.PRECIO)</th>
                        <th>@(d.CANTIDAD)</th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>