Lab10_MVCVentas_Sosa/Controllers/TipoUsuarioController.cs
using Modelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab10_MVCVentas_Sosa.Filters;

namespace Lab10_MVCVentas_Sosa.Controllers
{
    [Autenticado]
    public class TipoUsuarioController : Controller
    {
        private TIPO_USUARIO tipo_usuario = new TIPO_USUARIO();//Instancia la clase tipo usuario
        // GET: TipoUsuario
        public ActionResult Index(string criterio)
        {
            if (criterio == null || criterio == "")
            {
                return View(tipo_usuario.Listar());
            }
            else
            {
                return View(tipo_usuario.Buscar(criterio));
            }
        }

        public JsonResult CargarTipoUsuario(AnexGRID grid)
        {
            return Json(tipo_usuario.ListarTipoGrilla(grid));
        }

        //public JsonResult Listar(Model.AnexGRID agrid)
        //{
        //    return Json(empleado.Listar(agrid), JsonRequestBehavior.AllowGet);
        //}

        public ActionResult Ver(int id)
        {
            return View(tipo_usuario.Obtener(id));
        }

        public ActionResult AgregarEditar(int id = 0)
        {
            return View(
                id == 0 ? new TIPO_USUARIO() //para generar una nueva categoría
                        : tipo_usuario.Obtener(id) //retorna un id de una categoría existente
                );
        }

        public ActionResult Guardar(TIPO_USUARIO model)
        {
            if (ModelState.IsValid)
            {
                model.Guardar();
                return Redirect("~/TipoUsuario/Index"); //devuelve el index
            }
            else
            {
                return View("~/Views/TipoUsuario/AgregarEditar.cshtml", model);
            }
        }

        public ActionResult Eliminar(int id)
        {
            tipo_usuario.IDTIPOUSUARIO = id;
            tipo_usuario.Eliminar();
            return Redirect("~/TipoUsuario/Index"); //devuelve el index
        }

        public ActionResult Buscar(string criterio)
        {
            return View(
                    criterio == null || criterio == "" ? tipo_usuario.Listar()//devuelve la lista completa
                    : tipo_usuario.Buscar(criterio)//devuelve la lista en base a la búsqueda
                    );
        }
    }
}

Lab10_MVCVentas_Sosa/Views/TipoUsuario/AgregarEditar.cshtml
@model Modelo.TIPO_USUARIO
@{
    ViewBag.Title = (Model.IDTIPOUSUARIO > 0 ? Model.NOMBRE : "Nuevo Registro");
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">Agregar/Editar Tipo Usuario</h2>

<ol class="breadcrumb">
    <li>
        <a href="~/TipoUsuario/">Tipo de Usuario</a>
    </li>
    <li class="active">
        @(Model.IDTIPOUSUARIO > 0 ? Model.NOMBRE : "Nuevo Registro")
    </li>
</ol>

@using (Html.BeginForm("Guardar", "TipoUsuario", FormMethod.Post, new { id = "frm-tipousuario" }))
{
    @Html.HiddenFor(x => x.IDTIPOUSUARIO)

    <div class="panel panel-primary">
        <div class="panel-heading">
            Información del Tipo de Usuario
        </div>
        <div class="panel-body">
            <div class="form-group">
                @Html.LabelFor(x => x.IDTIPOUSUARIO)
                @Html.TextBoxFor(x => x.IDTIPOUSUARIO, new { @class = "form-control", disabled = true })
                @Html.ValidationMessageFor(x => x.IDTIPOUSUARIO, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.NOMBRE)
                @Html.TextBoxFor(x => x.NOMBRE, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NOMBRE, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.ESTADO)
                <select name="estado" class="form-control">
                    <option @(Model.ESTADO == "A" ? "selected" : "") value="A">Activo</option>
                    <option @(Model.ESTADO == "I" ? "selected" : "") value="I">Inactivo</option>
                </select>
                @Html.ValidationMessageFor(x => x.ESTADO, null, new { @class = "label label-danger" })
            </div>
        </div>
    </div>

    <div class="text-right">
        <button type="submit" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span></button>
        <a href="~/TipoUsuario/Index" class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-floppy-remove" aria-hidden="true"></span></a>
    </div>
}

Lab10_MVCVentas_Sosa/Views/TipoUsuario/Buscar.cshtml
@model List<Modelo.TIPO_USUARIO>
@{
    ViewBag.Title = "Buscar";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">
    <a href="~/TipoUsuario/AgregarEditar/" class="btn btn-success pull-right">Nuevo Tipo Usuario</a>Tipos de Usuarios
</h2>

@using (Html.BeginForm("Buscar", "TipoUsuario", FormMethod.Post, new { criterio = "frm-buscar" }))
{
    <div class="text-left">
        @Html.Label("Buscar: ")
        @Html.TextBox("criterio", null)
        <button type="submit" class="btn btn-lg btn-warning pull-right"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
}
<br />

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width:50px;">Id</th>
                <th style="width:200px;">Nombre</th>
                <th style="width:50px;">Estado</th>
                <th style="width:50px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <th>@(m.IDTIPOUSUARIO)</th>
                    <th>@(m.NOMBRE)</th>
                    <th>@(m.ESTADO == "A" ? "Activo" : "Inactivo")</th>
                </tr>
            }
        </tbody>
    </table>
</div>

Lab10_MVCVentas_Sosa/Views/TipoUsuario/Index.cshtml
@model List<Modelo.TIPO_USUARIO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">
    <a href="~/TipoUsuario/AgregarEditar/" class="btn btn-lg btn-success pull-right"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a>Tipos de Usuarios
</h2>

@using (Html.BeginForm("Buscar", "TipoUsuario", FormMethod.Post, new { criterio = "frm-buscar" }))
{
    <div class="text-left">
        @Html.Label("Buscar: ")
        @Html.TextBox("criterio", null)
        <button type="submit" class="btn btn-lg btn-warning pull-right"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
}
<br />

<div class="list-group" id="list"></div>

<script>
    $(document).ready(function () {
        $("#list").anexGrid({
            class: 'table-striped table-hover table-condensed',
            columnas: [
                //columna1: ID
                { leyenda: "IDTIPOUSUARIO", columna: "IDTIPOUSUARIO", ordenable: true },
                //columna1: Nombre
                { leyenda: "NOMBRE", columna: "NOMBRE", ordenable: true },
                //columna1: Estado
                { leyenda: "ESTADO", columna: "ESTADO", ordenable: true },
                //Columnas de los botones
                { style: 'Width: 80px;' },//Visualizar
                { style: 'Width: 80px;' },//Modificar
                { style: 'Width: 80px;' },//Eliminar
            ],

            modelo: [
                //campo 1: IDTIPOUSUARIO
                { propiedad: 'IDTIPOUSUARIO' },
                //campo 2: NOMBRE
                {
                    propiedad: 'NOMBRE', formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/TipoUsuario/AgregarEditar/")' + obj.IDTIPOUSUARIO,
                            contenido: valor
                        });
                    }
                },
                //Campo 3: ESTADO
                {
                    propiedad: 'ESTADO', formato: function (tr, obj, valor) {
                        return valor == "A" ? "Activo" : "Inactivo"
                    }
                },

                //para los botones
                //Botón Visualizar
                {
                    formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/TipoUsuario/Ver/")' + obj.IDTIPOUSUARIO,
                            contenido: '<i class="glyphicon glyphicon-eye-open" aria-hidden="true"></i>',
                            class: 'btn btn-lg btn-primary'
                        });
                    },
                },
                //Botón Modificar
                {
                    formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/TipoUsuario/AgregarEditar/")' + obj.IDTIPOUSUARIO,
                            contenido: '<i class="glyphicon glyphicon-pencil" aria-hidden="true"></i>',
                            class: 'btn btn-lg btn-info'
                        });
                    },
                },
                //Botón Eliminar
                {
                    formato: function (tr, obj, valor) {
                        return anexGrid_link({
                            href: '@Url.Content("~/TipoUsuario/Eliminar/")' + obj.IDTIPOUSUARIO,
                            contenido: '<i class="glyphicon glyphicon-trash" aria-hidden="true"></i>',
                            class: 'btn btn-lg btn-danger',
                            attr: [
                            'onclick="return confirm(\'¿Está seguro de eliminar el registro?\')"'
                            ]
                        });
                    },
                }
            ],
            url: '@Url.Content("~/TipoUsuario/CargarTipoUsuario/")',
            paginable: true,
            limite: [10, 20, 50, 100],
            columna: 'IDTIPOUSUARIO',
            columna_orden: "DESC"
        });
    })
</script>

Lab10_MVCVentas_Sosa/Views/TipoUsuario/Ver.cshtml
@model Modelo.TIPO_USUARIO
@{
    ViewBag.Title = "Ver";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">Ver Tipo Usuario</h2>

<ol class="breadcrumb">

    <li><a href="~/TipoUsuario/">Tipo Usuario</a></li>
    <li class="active">@Model.NOMBRE</li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading">
        Información de los Tipos de Usuarios
    </div>
    <div>
        <dl class="dl-horizontal">
            <dt>ID</dt>
            <dd>@Model.IDTIPOUSUARIO</dd>
            <dt>NOMBRE</dt>
            <dd>@Model.NOMBRE</dd>
            <dt>ESTADO</dt>
            <dd>@Model.ESTADO</dd>
        </dl>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        Usuarios
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width:50px;">Id</th>
                    <th style="width:50px;">Tipo Usuario</th>
                    <th style="width:200px;">Nombre</th>
                    <th style="width:200px;">Apellidos</th>
                    <th style="width:200px;">Email</th>
                    <th style="width:50px;">Estado</th>
                    <th style="width:50px;"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var u in Model.USUARIO)
                {
                    <tr>
                        <th>@(u.IDUSUARIO)</th>
                        <th>@(u.IDTIPOUSUARIO)</th>
                        <th>@(u.NOMBRE)</th>
                        <th>@(u.APELLIDOS)</th>
                        <th>@(u.EMAIL)</th>
                        <th>@(u.ESTADO == "A" ? "Activo" : "Inactivo")</th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>