Lab10_MVCVentas_Sosa/Controllers/CategoriaController.cs
using Modelo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab10_MVCVentas_Sosa.Filters;

namespace Lab10_MVCVentas_Sosa.Controllers
{
    [Autenticado]
    public class CategoriaController : Controller
    {
        private CATEGORIA categoria = new CATEGORIA();//Instancia la clase categoría
        // GET: Categoria
        public ActionResult Index(string criterio)
        {
            if (criterio == null || criterio == "")
            {
                return View(categoria.Listar());
            }
            else
            {
                return View(categoria.Buscar(criterio));
            }
        }

        public ActionResult Consulta()
        {
            return View(categoria.Consulta());
        }

        public ActionResult Ver(int id)
        {
            return View(categoria.Obtener(id));
        }

        public ActionResult AgregarEditar(int id = 0)
        {
            return View(
                id == 0 ? new CATEGORIA() //para generar una nueva categoría
                        : categoria.Obtener(id) //retorna un id de una categoría existente
                );
        }

        public ActionResult Guardar(CATEGORIA model)
        {
            if (ModelState.IsValid)
            {
                model.Guardar();
                return Redirect("~/Categoria/Index"); //devuelve el index
            }
            else
            {
                return View("~/Views/Categoria/AgregarEditar.cshtml", model);
            }
        }

        public ActionResult Eliminar(int id)
        {
            categoria.IDCATEGORIA = id;
            categoria.Eliminar();
            return Redirect("~/Categoria/Index"); //devuelve el index
        }

        public ActionResult Buscar(string criterio)
        {
            return View(
                    criterio == null || criterio == "" ? categoria.Listar()//devuelve la lista completa
                    : categoria.Buscar(criterio)//devuelve la lista en base a la búsqueda
                    );
        }
    }
}

Lab10_MVCVentas_Sosa/Views/Categoria/AgregarEditar.cshtml
@model Modelo.CATEGORIA
@{
    ViewBag.Title = (Model.IDCATEGORIA > 0 ? Model.NOMBRE : "Nuevo Registro");
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">Agregar/Editar Categoria</h2>

<ol class="breadcrumb">
    <li>
        <a href="~/Categoria/">Categorías</a>
    </li>
    <li class="active">
        @(Model.IDCATEGORIA > 0 ? Model.NOMBRE : "Nuevo Registro")
    </li>
</ol>

@using (Html.BeginForm("Guardar", "Categoria", FormMethod.Post, new { id = "frm-categoria" }))
{
    @Html.HiddenFor(x => x.IDCATEGORIA)

    <div class="panel panel-default">
        <div class="panel-heading">
            Información de la Categoría
        </div>
        <div class="panel-body">
            <div class="form-group">
                @Html.LabelFor(x => x.IDCATEGORIA)
                @Html.TextBoxFor(x => x.IDCATEGORIA, new { @class = "form-control", disabled = true })
            </div>
            <div>
                @Html.LabelFor(x => x.NOMBRE)
                @Html.TextBoxFor(x => x.NOMBRE, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.NOMBRE, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.DESCRIPCION)
                @Html.TextAreaFor(x => x.DESCRIPCION, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => x.DESCRIPCION, null, new { @class = "label label-danger" })
            </div>
            <div>
                @Html.LabelFor(x => x.ESTADO)
                <select name="estado" class="form-control">
                    <option @(Model.ESTADO == "A" ? "selected" : "") value="A">Activo</option>
                    <option @(Model.ESTADO == "I" ? "selected" : "") value="I">Inactivo</option>
                </select>
                @Html.ValidationMessageFor(x => x.ESTADO, null, new { @class = "label label-danger" })
            </div>
        </div>
    </div>

    <div class="text-right">
        <button type="submit" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-floppy-save" aria-hidden="true"></span></button>
        <a href="~/Categoria/Index" class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-floppy-remove" aria-hidden="true"></span></a>
    </div>
}

Lab10_MVCVentas_Sosa/Views/Categoria/Buscar.cshtml
@model List<Modelo.CATEGORIA>
@{
    ViewBag.Title = "Buscar Categoría";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">
    Búsqueda de Categorías
</h2>

@using (Html.BeginForm("Buscar", "Categoria", FormMethod.Post, new { criterio = "frm-buscar" }))
{
    <div class="text-left">
        @Html.Label("Buscar: ")
        @Html.TextBox("criterio", null)
        <button type="submit" class="btn btn-lg btn-warning pull-right"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
}
<br />

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width:50px;">Id</th>
                <th style="width:200px;">Nombre</th>
                <th style="width:200px;">Descripción</th>
                <th style="width:50px;">Estado</th>
                <th style="width:50px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <th>@(m.IDCATEGORIA)</th>
                    <th>@(m.NOMBRE)</th>
                    <th>@(m.DESCRIPCION)</th>
                    <th>@(m.ESTADO == "A" ? "Activo" : "Inactivo")</th>
                </tr>
            }
        </tbody>
    </table>
</div>

Lab10_MVCVentas_Sosa/Views/Categoria/Consulta.cshtml
@model string[,]
@{
    ViewBag.Title = "Consulta";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/exporting.js"></script>

<div class="table-responsive table-hover">
    <h1 class="page-header">Consulta</h1>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Cantidad</th>
            </tr>
        </thead>
        <tbody>
            @{ int cant = Model.GetUpperBound(0); }
            @for (int i = 0; i <= cant; i++)
            {
                <tr>
                    <td>@(Model[i, 0])</td>
                    <td>@(Model[i, 1])</td>
                    <td>@(Model[i, 2])</td>
                </tr>
            }
        </tbody>
    </table>
</div>

@*<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
    google.load("visualization", "1", { packages: ["corechart"] });
    google.setOnLoadCallback(dibujarGrafico);
    function dibujarGrafico() {
        // Tabla de datos: valores y etiquetas de la gráfica
        var data = google.visualization.arrayToDataTable([
          ['Texto', 'Valor numérico'],
          ['Texto1', 20.21],
          ['Texto2', 4.28],
          ['Texto3', 17.26],
          ['Texto4', 10.25]
        ]);
        var options = {
            title: 'Nuestro primer ejemplo con Google Charts'
        }
        // Dibujar el gráfico
        new google.visualization.ColumnChart(
        //ColumnChart sería el tipo de gráfico a dibujar
          document.getElementById('GraficoGoogleChart-ejemplo-1')
        ).draw(data, options);
    }
</script>
<body>
    Comenzando con Google Charts....
    <div id="GraficoGoogleChart-ejemplo-1" style="width: 800px; height: 600px">
    </div>
</body>*@

@*<body>
    <hr />
    <button type="button" id="btnGrafico">LLenar Gráfico</button>
    <hr />
    <div id="grafico"></div>

    <script>
        $(document).ready(function () {
            $("#btnGrafico").click("click", function () {
                ListarCategorias();
            });
        });

        function ListarCategorias() {
            $.ajax({
                type: "POST",
                contentType: "application/json; charset=utf-8",
                url: "~/Categoria/Consulta",
                data: "{}",
                dataType: "json",
                success: function (Result) {
                    Result = Result.d;
                    var data = [];
                    for (var i in Result) {
                        var serie = new Array(Result[i].nom_categoria, Result[i].id_categoria);
                        data.push(serie);
                    }
                    DibujaGrafico(data);
                    //DreawChartPubli(data, 'container2');
                },
                error: function (Result) {
                    alert("Error");
                }
            });
        }

        function DibujaGrafico(series) {
            $('#grafico').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: 1,//null,
                    plotShadow: false
                },
                title: {
                    text: 'Publicidad en mi web 2013 - 2014'
                },
                subtitle: {
                    text: 'mipagina.com'
                },
                tooltip: {
                    pointFormat: '{series.nom_categoria}: {point.y} (<b>{point.percentage:.1f}%</b>)'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.nom_categoria}</b>: {point.y}',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        }
                    }
                },
                series: [{
                    type: 'pie',
                    name: 'Publicidad',
                    data: series
                }]
            });
        }
    </script>
</body>*@

Lab10_MVCVentas_Sosa/Views/Categoria/Index.cshtml
@model List<Modelo.CATEGORIA>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">
    <a href="~/Categoria/AgregarEditar" class="btn btn-lg btn-success pull-right"><span class="glyphicon glyphicon-file" aria-hidden="true"></span></a>Categorías
</h2>

@using (Html.BeginForm("Buscar", "Categoria", FormMethod.Post, new { criterio = "frm-buscar" }))
{
    <div class="text-left">
        @Html.Label("Buscar: ")
        @Html.TextBox("criterio", null)
        <button type="submit" class="btn btn-lg btn-warning pull-right"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
    </div>
}
<br />

<div class="table-responsive">
    <table class="table table-hover">
        <thead>
            <tr>
                <th style="width:50px;">Id</th>
                <th style="width:200px;">Nombre</th>
                <th style="width:200px;">Descripción</th>
                <th style="width:50px;">Estado</th>
                <th style="width:50px;"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var m in Model)
            {
                <tr>
                    <th>@(m.IDCATEGORIA)</th>
                    <th>@(m.NOMBRE)</th>
                    <th>@(m.DESCRIPCION)</th>
                    <th>@(m.ESTADO == "A" ? "Activo" : "Inactivo")</th>

                    <th>
                        <a href="~/Categoria/Ver/@m.IDCATEGORIA" class="btn btn-lg btn-primary"><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></a>
                        <a href="~/Categoria/AgregarEditar/@m.IDCATEGORIA" class="btn btn-lg btn-info"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                        <a onclick="return confirm('¿Está seguro de eliminar el registro...?');" class="btn btn-lg btn-danger" href="~/Categoria/Eliminar/@m.IDCATEGORIA"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </th>
                </tr>
            }
        </tbody>
    </table>
</div>

Lab10_MVCVentas_Sosa/Views/Categoria/Ver.cshtml
@model Modelo.CATEGORIA
@{
    ViewBag.Title = "Ver";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2 class="page-header">Ver Categoria</h2>

<ol class="breadcrumb">

    <li><a href="~/Categoria/">Categorías</a></li>
    <li class="active">@Model.NOMBRE</li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading">
        Información de la Categoría
    </div>
    <div>
        <dl class="dl-horizontal">
            <dt>ID</dt>
            <dd>@Model.IDCATEGORIA</dd>
            <dt>CATEGORIA</dt>
            <dd>@Model.NOMBRE</dd>
            <dt>DESCRIPCION</dt>
            <dd>@Model.DESCRIPCION</dd>
            <dt>ESTADO</dt>
            <dd>@Model.ESTADO</dd>
        </dl>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        Productos
    </div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th style="width:50px;">Id</th>
                    <th style="width:200px;">Nombre</th>
                    <th style="width:200px;">Descripción</th>
                    <th style="width:50px;">Precio</th>
                    <th style="width:50px;"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var p in Model.PRODUCTO)
                {
                    <tr>
                        <th>@(p.IDPRODUCTO)</th>
                        <th>@(p.NOMBRE)</th>
                        <th>@(p.DESCRIPCION)</th>
                        <th>@(p.PRECIO)</th>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>